import { FileText } from "lucide-react";

import { Link } from "react-router-dom";
const Report = () => {
    return (
        <div className="flex items-center space-x-4 rounded-md border p-4">
            <FileText />
            <div className="flex-1 space-y-1">
                <p className="text-sm font-medium leading-none">
                    New York Property Analysis Q1
                </p>
                <p className="text-sm text-muted-foreground">
                    Generated by John Doe • 1 day ago
                </p>
            </div>
            <Link to={`#`} className="text-sm hover:text-primary duration-200">
                View
            </Link>
        </div>
    );
};
export default Report;
